let allMusic = [
  {
    name: "Why'd Ya Start the Fire",
    artist: "Reluctant Heroes",
    img: "album-1",
    src: "whyd-ya-start-the-fire",
    album: "Life in Open G",
  },
  {
    name: "First World State of Mind",
    artist: "Reluctant Heroes",
    img: "album-1",
    src: "first-world-state-of-mind",
    album: "Life in Open G",
  },
  {
    name: "Holding You",
    artist: "Reluctant Heroes",
    img: "album-1",
    src: "holding-you",
    album: "Life in Open G",
  },
  {
    name: "Show You What Its Like",
    artist: "Reluctant Heroes",
    img: "album-1",
    src: "show-you-what-its-like",
    album: "Life in Open G",
  },
  {
    name: "Social Media Post",
    artist: "Reluctant Heroes",
    img: "album-1",
    src: "social-media-post",
    album: "Life in Open G",
  },
  {
    name: "Poet with a Tune",
    artist: "Reluctant Heroes",
    img: "album-1",
    src: "poet-with-a-tune",
    album: "Life in Open G",
  },
  {
    name: "Bottom Line",
    artist: "Reluctant Heroes",
    img: "album-1",
    src: "bottom-line",
    album: "Life in Open G",
  },
  {
    name: "Don't Feel Much Like Dancin'",
    artist: "Reluctant Heroes",
    img: "album-1",
    src: "dont-feel-much-like-dancin",
    album: "Life in Open G",
  },
  {
    name: "No Regrets",
    artist: "Reluctant Heroes",
    img: "album-1",
    src: "no-regrets",
    album: "Life in Open G",
  },
  {
    name: "Good as Bad News Gets",
    artist: "Reluctant Heroes",
    img: "album-1",
    src: "good-as-bad-news-gets",
    album: "Life in Open G",
  },
  {
    name: "Smoke and Mirrors",
    artist: "Reluctant Heroes",
    img: "album-1",
    src: "smoke-and-mirrors",
    album: "Life in Open G",
  },
  {
    name: "Lifeline",
    artist: "Reluctant Heroes",
    img: "album-1",
    src: "lifeline",
    album: "Life in Open G",
  },
  {
    name: "Familiar Tune",
    artist: "Reluctant Heroes",
    img: "album-1",
    src: "familiar-tune",
    album: "Life in Open G",
  },
  {
    name: "Blues Man",
    artist: "Reluctant Heroes",
    img: "album-2",
    src: "blues-man",
    album: "Album 2",
  },
  {
    name: "Memories",
    artist: "Reluctant Heroes",
    img: "album-2",
    src: "memories",
    album: "Album 2",
  },
  {
    name: "How Good",
    artist: "Reluctant Heroes",
    img: "album-2",
    src: "how-good",
    album: "Album 2",
  },
  {
    name: "Simpler Times",
    artist: "Reluctant Heroes",
    img: "album-2",
    src: "simpler-times",
    album: "Album 2",
  },
  {
    name: "Maybe You'll See the Light",
    artist: "Reluctant Heroes",
    img: "album-2",
    src: "maybe-youll-see-the-light",
    album: "Album 2",
  },
];
